import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/component/provider/ThemeProvider";
import MiniSideBar from "@/component/MiniSideBar";
import MaxSidebar from "@/component/MaxSidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "project UI panel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider 
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange>
            <div className="flex fixed top-0 left-0 bottom-0">
            <MiniSideBar />
            <MaxSidebar />
          </div>
          <main className="ml-85 "
          >{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
